name: Documentation

on:
  push:
    branches:
      - master
      - main
    paths:
      - "CHANGELOG.md"
      - docs/**
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-doc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@main
        with:
          python-version: 3.x
          cache: true
      - name: Build pages
        run: |
          pdm install -G docs
          pdm run docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/site
