name: Update session status

on: 
  schedule:
    # every 12 hours
    - cron: '0 */6 * * *'
  push:
    branches: [ "main" ]
    paths:
      - 'tracked_sessions.yaml'
    tags:        
      - '*'           # Push events to every tag not containing /
  
  workflow_dispatch:
  
jobs:
  package:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9"]
    permissions: write-all

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install package
      run: |
        pip install -e .[polars]
    
    - name: Update session status
      env:
        DBHUB_API_KEY: ${{ secrets.DBHUB_API_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        CODE_OCEAN_API_TOKEN: ${{ secrets.CODE_OCEAN_API_TOKEN }}
        CODE_OCEAN_DOMAIN: ${{ secrets.CODE_OCEAN_DOMAIN }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        REDIS_DEFAULT_USER_PASSWORD: ${{ secrets.REDIS_DEFAULT_USER_PASSWORD }}
      run: |
        update_session_status
